version: '3.8'
services:
  main:
    image: main-sbt:latest
    depends_on:
      - player
      - card
    stdin_open: true
    ports:
      - "8080:8080"
  player:
    image: player-sbt:latest
    stdin_open: true
    depends_on:
      - card
    ports:
      - "8081:8081"
  card:
    image: card-sbt:latest
    stdin_open: true
    ports:
      - "8082:8082"

